### ISSUE TITLE
unable to compile using "make all"

### ISSUE THREAD

**Issue by syddo** [kcs/FreeRTOS-Xplained#1]
Hi @kcs ,

I have did a clone of your master branch and it seems like it is unable to compile properly.
I am new to RTOS and working on Xmega devices so your work is like my starting point.
THanks a lot.

error:

```
(CC) src/FreeRTOS/portable/port.c
src/FreeRTOS/portable/port.c: In function 'prvSetupTimerInterrupt':
src/FreeRTOS/portable/port.c:425:2: error: 'OCR1AH' undeclared (first use in this function)
  OCR1AH = ucHighByte;
  ^
src/FreeRTOS/portable/port.c:425:2: note: each undeclared identifier is reported only once for each function it appears in
src/FreeRTOS/portable/port.c:426:2: error: 'OCR1AL' undeclared (first use in this function)
  OCR1AL = ucLowByte;
  ^
src/FreeRTOS/portable/port.c:430:2: error: 'TCCR1B' undeclared (first use in this function)
  TCCR1B = ucLowByte;
  ^
src/FreeRTOS/portable/port.c:434:14: error: 'TIMSK' undeclared (first use in this function)
  ucLowByte = TIMSK;
              ^
src/FreeRTOS/portable/port.c: In function 'SIG_OUTPUT_COMPARE1A':
src/FreeRTOS/portable/port.c:448:7: error: 'SIG_OUTPUT_COMPARE1A' appears to be a misspelled signal handler, missing __vector prefix [-Werror=mi
  void SIG_OUTPUT_COMPARE1A( void )
       ^
cc1.exe: all warnings being treated as errors
makefile:221: recipe for target 'obj/port.o' failed
make: *** [obj/port.o] Error 1
```

**Comment by kcs** [comment]
Unfortunately this repo is still Work in Progress, I have not yet finished the porting entirely and in the meantime I got derailed by other tasks. I do intend to finish it, as I need this port for class, but I cannot foretell right now the timeframe for it. I will post and update when I got this working.

**Comment by syddo** [comment]
Thanks for the reply... I hope you won't mind if I try to continue your code. This is interesting and also vital as I have started to work with Xmega recently. I will just send a pull request if I get it to work.

**Comment by kcs** [comment]
not at all, feel free to use the code in whatever means suits you
the timer registers and the initialization routine needs to be changed (from ATmega registers to ATXmega registers), and also the makefile has some issues (which I have fixed in another project, but not yet pulled back here, but I will take care of this)

**Comment by syddo** [comment]
@kcs would it be possible if you can pull it here before I fork the repository. I hope i'm not asking too much. thanks!

**Comment by kcs** [comment]
yes no problem, but I can do it only tomorrow afternoon

**Comment by kcs** [comment]
@syddo I now updated the makefile and also fixed the compile errors, so now the demo is running ok on the target board, of couse it still does nothing useful, but you can easily use as a starting point for whatever you like to

**Comment by syddo** [comment]
@kcs thanks a lot.. i'll pull the changes and try this out. :)
